### ISSUE TITLE
Create sample data on start up

### ISSUE THREAD

**Issue by MartinStyk** [MartinStyk/pa165-activity-tracker#19]

**Comment by Ondrejkova** [comment]
I add sample data. And I have made test if data are already setup, but I have problem with running test.

**Comment by MartinStyk** [comment]
@Ondrejkova , I fixed this, please review my changes in a001dc97d61b46c8ce38b762df2381995534ef72.
I hit following issues
* calories computation was always zero for duration < then 1 hour - fixed here 6137b0a33cd3a585937f2748ca26e647baba0dab. This is the issue hit by you
* I changed test to use facade, sice there issome logic on service and facade. when using dao, teams and members were not set/read as expected
* There are issues with adding members to team. We need to set owning side, which is user. we need to persist that user is part of team, not the team contains users. This should be done on team facade now, but I have not tested in depth

**Comment by Ondrejkova** [comment]
Thank you very much, I reviewed changes and it have sence, so I think that samle data are ready and I can close this issue.

**Comment by MartinStyk** [comment]
Great first milestone 3 issue done, so we can close this.
Just correcting my prevoius comment. Issue hit by you was caused by creating sport yoga and loking for sport joga. Zero callories was another one.
