### ISSUE TITLE
Create sport activity entity class and DAO

### ISSUE THREAD

**Issue by MartinStyk** [MartinStyk/pa165-activity-tracker#3]

**Comment by Ondrejkova** [comment]
tests are added in commit b3f3193. ;)

**Comment by MartinStyk** [comment]
@adamlaurencik , is here something not done yet? Entity looks good to me, maybe somebody else could review as well. If you consider it is all done, please close this :+1:

**Comment by adamlaurencik** [comment]
Ok I am closing it I think everything is finished
