### ISSUE TITLE
Create sport activity record entity and DAO

### ISSUE THREAD

**Issue by MartinStyk** [MartinStyk/pa165-activity-tracker#5]

**Comment by Ondrejkova** [comment]
I think it is done in commit ee3275e.

**Comment by MartinStyk** [comment]
Hi, great job
- As @adamlaurencik said, we should use instanceof (not getClass()) and getters for objects in equals. It is beacuse Hibernate which creates proxies and it can cause problems. Also equals and hashcode should depend only on parameters we believe are distinct among two objects (this is satisfied, but I think user + startTime + endTime is good as well, but probably can stay like it is now)
- I have added some tests, 3 of them fail. It is related to input parameters check in dao methods. We should probably check parameter when EntityManager not check them for us - that is the case whne we use only TypedQuery, not EntityManager call (see 8d4d0a285a4b54c78de5a18e400d3c37ed19512d). (I said we dont have to check nulls, but it is strange when you call method with null parameter and it works :-). Sorry for that... )

When above points are done, we can probably close this 👍

**Comment by Ondrejkova** [comment]
All repair in commit 1796102.

**Comment by MartinStyk** [comment]
👍 Looks great, if you think your work on this issue is done, feel free to close it :)

**Comment by MartinStyk** [comment]
One more point, I added validation to have time order checking "more enterprise" (aeb9f9aef8cefde113a5885d2c07109ed847fb05). You can check it, I think it is nicer to have annotation than "ifs" in code, otherwise it was done just for fun 🎱
