### ISSUE TITLE
Create tests for sport activity DAO

### ISSUE THREAD

**Issue by MartinStyk** [MartinStyk/pa165-activity-tracker#7]
Test #3

**Comment by Ondrejkova** [comment]
Tests created in commit b3f3193.
Only one test testUpdateNotExistingSportActivity is missing.
@adamlaurencik  tests for your entity looks fine, there are 4 fails, but I think that if you add @Min(0) and @NotNull for atribute Double caloriesFactor. It should be ok. ;)

**Comment by MartinStyk** [comment]
I see all tests passes OK. I checked briefly and it seems it covers all necessary cases. Are you planning to add other tests, or we can close this?

**Comment by Ondrejkova** [comment]
Ok I close it. ;)

**Comment by Ondrejkova** [comment]
I delete coment in describtion of test. Final verse of test in commit ffc2c80.
